
name: Pull and Run Docker Image

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    branches: [main]
    types:
      - completed

jobs:
  pull-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    - name: Pull the Docker image
      run: docker pull ashivamdocker/ci_cd_docker:latest
    - name: Run the Docker image
      run: docker run --name test_container ashivamdocker/ci_cd_docker:latest
    - name: Check test results
      run: |
        if docker logs test_container | grep -q 'Score: 0.5'; then
          echo "Test passed with a score above 0.5"
        else
          echo "Test failed with a score below 0.5"
          exit 1
        fi
