name: test
on:
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - uses: actions/checkout@v3

    - name: Pull Docker Image
      run:  docker pull ashivamdocker/CICD_Assignment:latest

    - name: Run tests in Docker container
      run:  docker run --rm ashivamdocker/CICDAssignment:latest
